### ISSUE TITLE
Duplicate Clinical Notes in form_clinical_notes Table on 11k patients Instances

### ISSUE THREAD

**Issue by KeerthikaSunchu** [iupui-soic/openemr#28]
### Describe the bug
The form_clinical_notes table on both web12 and web13 contains duplicate entries for various descriptions.

### To Reproduce
![image](https://github.com/user-attachments/assets/66620fd0-a9c9-4197-8bb2-98b7849c29e8)

![image](https://github.com/user-attachments/assets/f3b6cb36-8e11-4d48-9371-fc96996c52a3)

1. Log into web12 or web13 OpenEMR database.
2. Navigate to the SQL Query section.
3. Execute the following query:
SELECT description, COUNT( * )
FROM form_clinical_notes
GROUP BY description
HAVING COUNT( * ) > 1;
5. Observe multiple records showing the same description with counts greater than 1.

### Expected behavior
Each clinical note's description should be unique, or the duplicates should be justified by different patient IDs or encounters. There should be no unintended duplication of note descriptions for the same patient encounter.

### Client configuration
- OpenEMR version: 7.0.2

**Comment by yywini** [comment]
**Solution Implemented**
To resolve this, I used the following SQL code to ensure that each duplicate description is modified slightly by appending an entry number, making each instance unique within its encounter:

UPDATE form_clinical_notes AS t1
JOIN (
    SELECT id, description, encounter, ROW_NUMBER() OVER(PARTITION BY encounter, description ORDER BY id) AS row_num
    FROM form_clinical_notes
) AS duplicates ON t1.id = duplicates.id
SET t1.description = CONCAT(t1.description, ' (Entry #', duplicates.row_num, ')')
WHERE duplicates.row_num > 1;

This code appends a unique entry number to each duplicate description within the same encounter, preserving the original descriptions while ensuring uniqueness.

**Verification**
To confirm the issue was resolved, I ran the following query to check for any remaining duplicates within the same encounter:

SELECT description, encounter, COUNT(*) AS duplicate_count
FROM form_clinical_notes 
GROUP BY description, encounter
HAVING COUNT(*) > 1;

After executing this query, no duplicates were found. Notably, this query is designed to identify duplicates only within the same encounter, meaning that any identical descriptions across different encounters or patients would not appear as duplicates in this view.
![Screenshot 2024-11-09 110843](https://github.com/user-attachments/assets/68a79f86-b4b5-47bf-86cc-a22cfdbb620d)

**Conclusion**
The issue of duplicate descriptions has been resolved by modifying descriptions to make each unique within the same encounter.
